channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.10
  - numpy
  - matplotlib
  - scipy
  - h5py
  - pytest
  - autopep8
  - cartopy
  - gdal
  - obspy
  - pip
  - pip:
    - sphinx<6.0
    - pydata-sphinx-theme
    - sphinx-design
    - numpydoc
    - -e .